### ISSUE TITLE
Cannot start docker container in testnet

### ISSUE THREAD

**Issue by bitperfect-tleung** [ndau/commands#15]
I am facing a issue that I cannot start a docker container in testnet, as the latest testnet snapshot form S3 is wrong.
`{"_msg":"Error in validation","err":"Invalid commit -- wrong set size: 7 vs 13","level":"error","module":"blockchain"}`

**Comment by edmcnierney** [comment]
Thanks very much for the report! Our snapshot server wasn't creating snapshots correctly. As a result, the "latest" snapshot was from a blockchain branch that has been replaced by a different one (on testnet only, of course). It's back online, and the problem should now be fixed if you try `runcontainer.sh` again.

**Comment by bitperfect-tleung** [comment]
@edmcnierney Thank you for your help! I have tried to rerun the `runcontainer.sh`, it seems the `latest-testnet.txt` updated, but the target `*.tgz` files are zero bytes size now.

**Comment by edmcnierney** [comment]
You're right - it looks like there's a new problem with them. But you can use the (good) snapshot `snapshot-testnet-419661` by specifying it on the `runcontainer.sh` command line. Let me know if that works while we look into this new problem.

**Comment by bitperfect-tleung** [comment]
@edmcnierney I can pull the snapshot now. However, I am facing other issue during running the testnet container.
```
{"level":"error","msg":"did not return ok","name":"claimerportclear","port":"$CLAIMER_PORT","status":"ErrorEvent 3 - listen tcp: address tcp/$CLAIMER_PORT: unknown port","time":"2021-11-12T16:34:16Z","type":"portavailable"}
{"error":"pinger failed: claimerportclear","level":"fatal","msg":"problems running prologue","time":"2021-11-12T16:34:16Z"}
```
Is there any suggestion for that? Many thanks.

**Comment by edmcnierney** [comment]
Your feedback is great, but you're having a little bad luck in your timing. We're just preparing a new testnet upgrade and you're getting caught in the middle a little bit.

ndau validator nodes are eligible to win node rewards, and they must explicitly claim them when they're nominated. This release includes a `claimer` process that will do that automatically, and that requires a few new configuration parameters for `runcontainer.sh`. The current release image on testnet has a bug. If you don't provide those parameters the `procmon` process monitor should not try to run the claimer process, but it does. That produces the error you're seeing, and `procmon` will shut down the container if it can't run all the processes it's configured to run.

The best solution is for you to just wait a day or two! We have the fix ready: we're just bundling it with a few other updates. I'll comment here when that new release is available on testnet, and you can try again. The `runcontainer.sh` script always uses the most current release of the ndau software so it isn't very easy to roll back to an earlier one.

**Comment by bitperfect-tleung** [comment]
I can sync with the latest block in testnet now. Thanks!

**Comment by edmcnierney** [comment]
You're welcome! I apologize for the delay - testnet should be stable now and this shouldn't happen again.
