### ISSUE TITLE
When running setup ./bin/setup.sh 1 " line 73: make: command not found"

### ISSUE THREAD

**Issue by protontopeon** [ndau/commands#26]
HEAD is now at c4ba93a1e set the date to today
SETUP: Updating commands...
From https://github.com/ndau/commands
 * branch            master     -> FETCH_HEAD
Already up to date.
SETUP: Updating ndau...
From https://github.com/ndau/ndau
 * branch            master     -> FETCH_HEAD
Already up to date.
SETUP: Ensuring dependencies for commands...
SETUP: Building...
building noms
building tendermint
/home/ndau/go/src/github.com/ndau/commands/bin/build.sh: line 73: make: command not found

**Comment by edmcnierney** [comment]
What operating system and version are you using?

**Comment by protontopeon** [comment]
Ubuntu 20.04 LTS

**Comment by edmcnierney** [comment]
Might be a server/desktop difference. It's pretty unusual for a development system to not make `make` installed.

`sudo apt install make`

**Comment by protontopeon** [comment]
that solved it, thank you, i will pay better attention to the error messages
