### ISSUE TITLE
runcontainer.sh producing unexpected loop

### ISSUE THREAD

**Issue by protontopeon** [ndau/commands#32]
when running 

**_./runcontainer.sh mainnet nodename 26660 26670 3030 node-identity-nodename.tgz "" "" "" "http://localhost:4040/claim_winner" 4040_**

node setup loops at the following below.  I have tried editing the watchcontainer.sh and I have tried adding the logfile in /image/logs neither have stopped the loop.

Waiting for the node to fully spin up...
Watching nodename...
Still waiting for nodename
Container logs...
> nodename is starting up
> Configuring node group...
> Fetching latest-mainnet.txt...
> Fetching snapshot-mainnet-539271.tgz...

Log files...
ls: /image/logs: No such file or directory
(none)

Still waiting for nodename
Container logs...
> nodename is starting up
> Configuring node group...
> Fetching latest-mainnet.txt...
> Fetching snapshot-mainnet-539271.tgz...

Log files...
ls: /image/logs: No such file or directory
(none)

**Comment by edmcnierney** [comment]
This is correct behavior; it's always done that. It's waiting for the node to come up and be completely running. As our database and snapshot files get larger (a snapshot is now 21.9 GB) it just takes longer.

**Comment by protontopeon** [comment]
ok, I wasn't sure by the messages.  Maybe we can add something to the script to let users know whats happening.
"Downloading and expanding blockchain, no progress bar, this will take a while just let it run until its finished."
