### ISSUE TITLE
Recognize failed transaction?

### ISSUE THREAD

**Issue by anhcao142** [ndau/commands#5]
Hi, is there a way to recognize failed transactions from this API https://github.com/ndau/commands/tree/master/cmd/ndauapi#transactionbyhash?

**Comment by jsgjnr** [comment]
This API will only recognize successful transactions, as only a successful transaction will return a hash.  The only way to recognize a failed transaction is with a non-zero error code returned from either the https://github.com/ndau/commands/tree/master/cmd/ndauapi#txprevalidate endpoint or the https://github.com/ndau/commands/tree/master/cmd/ndauapi#txsubmit endpoint.

Let me know if you have additional questions.

— John

**Comment by anhcao142** [comment]
Thanks, it's good to know that the API only returns successful transaction.
